objs:

    'bottle':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/bottle.xml'
    'bottle4':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/bottle4.xml'
    'bottle3':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/bottle3.xml'
    'bottle2':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/bottle2.xml'
    '2d4ccc24a821360f8acb0ff76f4aec7d':
        class_id: 7
        obj_xml_file: 'car/2d4ccc24a821360f8acb0ff76f4aec7d.xml'
        scale: 1.2
    '2e8c4fd40a1be2fa5f38ed4497f2c53c':
        class_id: 7
        obj_xml_file: 'car/2e8c4fd40a1be2fa5f38ed4497f2c53c.xml'
        scale: 1.2
    '306f684fa89eb73ee151bdef07e713a2':
        class_id: 7
        obj_xml_file: 'car/306f684fa89eb73ee151bdef07e713a2.xml'
        scale: 1.2
    '312cfe616ce515be5826faa473422ba6':
        class_id: 7
        obj_xml_file: 'car/312cfe616ce515be5826faa473422ba6.xml'
        scale: 1.2
    '3d693af6fbae47f9cfb661f69a0dfbbd':
        class_id: 7
        obj_xml_file: 'car/3d693af6fbae47f9cfb661f69a0dfbbd.xml'
        scale: 1.2

    '1071fa4cddb2da2fc8724d5673a063a6':
        class_id: 7
        obj_xml_file: 'bottles/1071fa4cddb2da2fc8724d5673a063a6.xml'
        scale: 1.0
    #10
    '13d991326c6e8b14fce33f1a52ee07f2':
        class_id: 7
        obj_xml_file: 'bottles/13d991326c6e8b14fce33f1a52ee07f2.xml'
        scale: 1.2
    '1cf98e5b6fff5471c8724d5673a063a6':
        class_id: 7
        obj_xml_file: 'bottles/1cf98e5b6fff5471c8724d5673a063a6.xml'
        scale: 1.2
    '1df41477bce9915e362078f6fc3b29f5':
        class_id: 7
        obj_xml_file: 'bottles/1df41477bce9915e362078f6fc3b29f5.xml'
        scale: 1.2

    '21dbbd17ae4c3fce6a90f735365ac29e':
        class_id: 7
        obj_xml_file: 'bottles/21dbbd17ae4c3fce6a90f735365ac29e.xml'
        scale: 0.6

    'camera2':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/camera2.xml'

    'camera':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/camera.xml'
    'nail6':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/nail6.xml'
    'nail5':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/nail5.xml'
    'nail4':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/nail4.xml'
    'nail3':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/nail3.xml'
    #20
    'nail2':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/nail2.xml'
    'nail1':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/nail1.xml'
    'hammer8':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/hammer8.xml'
    'hammer7':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/hammer7.xml'
    'hammer6':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/hammer6.xml'
    'hammer5':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/hammer5.xml'

    'hammer4':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/hammer4.xml'

    'hammer3':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/hammer3.xml'

    'hammer2':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/hammer2.xml'

    'hammer':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/hammer.xml'
    #30
# 5 bus
    '1004ae81238886674d44f5db04bf14b8':
        class_id: 7
        obj_xml_file: 'bus/1004ae81238886674d44f5db04bf14b8.xml'
        scale: 1.2
    '239f4f66030286e73a304988a6618a7b':
        class_id: 7
        obj_xml_file: 'bus/239f4f66030286e73a304988a6618a7b.xml'
        scale: 1.2
    'f30209622ad392b1dca398a9db6025b3':
        class_id: 7
        obj_xml_file: 'bus/f30209622ad392b1dca398a9db6025b3.xml'
        scale: 2.0
    'f9c9cb740629615426479a182158bae5':
        class_id: 7
        obj_xml_file: 'bus/f9c9cb740629615426479a182158bae5.xml'
        scale: 1.0    
    '6929f0a74db347dcc69634f1103db34e':
        class_id: 7
        obj_xml_file: 'bus/6929f0a74db347dcc69634f1103db34e.xml'
        scale: 1.5
 #13 cans
    '60f4012b5336902b30612f5c0ef21eb8':
        class_id: 8
        obj_xml_file: 'can/60f4012b5336902b30612f5c0ef21eb8.xml'
        scale: 1.2
    '669033f9b748c292d18ceeb5427760e8':
        class_id: 8
        obj_xml_file: 'can/669033f9b748c292d18ceeb5427760e8.xml'
        scale: 1.2
    '6f2c06bb129e52be63ed57e35c972b4b':
        class_id: 8
        obj_xml_file: 'can/6f2c06bb129e52be63ed57e35c972b4b.xml'
        scale: 1.2

    '7e9ea6ccb5a1689a3299d37e620d2f2':
        class_id: 8
        obj_xml_file: 'can/7e9ea6ccb5a1689a3299d37e620d2f2.xml'
        scale: 1.2
    '8cf26f6912f4a9e34a045a96d74810ea':
        class_id: 8
        obj_xml_file: 'can/8cf26f6912f4a9e34a045a96d74810ea.xml'
        scale: 1.2
    # 40
    '9b1f0ddd23357e01a81ec39fd9664e9b':
        class_id: 8
        obj_xml_file: 'can/9b1f0ddd23357e01a81ec39fd9664e9b.xml'
        scale: 0.8
    'ac66fb0ff0d50368ced499bff9a86355':
       class_id: 8
       obj_xml_file: 'can/ac66fb0ff0d50368ced499bff9a86355.xml'
       scale: 1.2

    'ace554442d7d530830612f5c0ef21eb8':
        class_id: 8
        obj_xml_file: 'can/ace554442d7d530830612f5c0ef21eb8.xml'
        scale: 1.2

    'adaaccc7f642dee1288ef234853f8b4d':
        class_id: 8
        obj_xml_file: 'can/adaaccc7f642dee1288ef234853f8b4d.xml'
        scale: 1.2

    'b36902ae19ac77f2a89caedb1243a99':
        class_id: 8
        obj_xml_file: 'can/b36902ae19ac77f2a89caedb1243a99.xml'
        scale: 1.2

    'd44cec47dbdead7ca46192d8b30882':
        class_id: 8
        obj_xml_file: 'can/d44cec47dbdead7ca46192d8b30882.xml'
        scale: 1.2

    'd801d5b05f7d872341d8650f1ad40eb1':
        class_id: 8
        obj_xml_file: 'can/d801d5b05f7d872341d8650f1ad40eb1.xml'
        scale: 1.2

    'd801d5b05f7d872341d8650f1ad40eb1':
        class_id: 8
        obj_xml_file: 'can/d801d5b05f7d872341d8650f1ad40eb1.xml'
        scale: 1.2
    'pen':
        class_id: 2
        obj_xml_file: 'robotsuite_objects_centered/pen.xml'
    'dice':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered/dice.xml'
    #50
    'glass':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered/glass.xml'

    'spray':
       class_id: 2
       obj_xml_file: 'robotsuite_objects_centered2/spray.xml'