max_path_length: 50
num_rollouts: 5
accept_threshold: 0.8 #evaluate all
env_name: 'FetchPickAndPlace-v1'
env_base_xml_file: 'fetch/pick_and_place_stiff_table_kp10000.xml'
n_robot_dof: 8
init_info: {'center_of_table': [1.3, 0.75, 0.4],
            'objs': {'object0': {'pos': "-0.08#0.08 -0.15#0.15 0.1" }}
           }

#            'objs': {'object0': {'pos': "0.15 -0.1 0.2", 'euler_zyx': "60 -90 0" }}
#init_info: {'center_of_table': [1.3, 0.75, 0.4],
#            #'objs': {'object0': {'pos': "0.15 -0.1 0.2", 'euler_zyx': "60 -90 0" }}
#            'objs': {'object0': {'pos': "0 -0.1 0.2", 'euler_zyx': "60 0 -90" }}
#           }
#-0.15#0.15 -0.15#
#"-0.15#0.20 -0.3#0.3 0.1"
#"0#360 0#90 0"

render: False
bbox_indicator: False
randomize_color: True

initial_policies:
    #ddpg_fetch_cup_less_obs_159e56c18906830278d8f8c02c47cde0:
    #    fn: policy.pytorch_policy:PytorchPolicy
    #    params:
    #        policy_model_path: "fetch_cup_less_obs/159e56c18906830278d8f8c02c47cde0"
    #        #obs_arg: "25"
    #
    #ddpg_fetch_cups_b9004dcda66abf95b99d2a3bbaea842a:
    #    fn: policy.pytorch_policy:PytorchPolicy
    #    params:
    #        policy_model_path: "cups/b9004dcda66abf95b99d2a3bbaea842a"
    #        obs_arg: "25"
           #model_name: save50 #can specify which one do you like, or I will take the latest one

    grasp_6dgrasp_controller:
        fn: policy.grasp_6dgrasp_controller:Grasp6DGraspController
        params:
            max_path_length: 110

