max_path_length: 50
num_rollouts: 5
accept_threshold: 0.8 #evaluate all
env_name: 'FetchPickAndPlace-v1'
env_base_xml_file: 'fetch/pick_and_place_stiff_table_kp10000.xml'
n_robot_dof: 8
init_info: {'center_of_table': [1.3, 0.75, 0.4],
            'objs': {'object0': {'pos': "-0.08#0.08 -0.15#0.15 0.1" }}
           }

#            'objs': {'object0': {'pos': "0.15 -0.1 0.2", 'euler_zyx': "60 -90 0" }}
#init_info: {'center_of_table': [1.3, 0.75, 0.4],
#            #'objs': {'object0': {'pos': "0.15 -0.1 0.2", 'euler_zyx': "60 -90 0" }}
#            'objs': {'object0': {'pos': "0 -0.1 0.2", 'euler_zyx': "60 0 -90" }}
#           }
#-0.15#0.15 -0.15#
#"-0.15#0.20 -0.3#0.3 0.1"
#"0#360 0#90 0"

# camera params
camera_img_height: 128
camera_img_width: 128
camera_radius: 0.3
camera_fov_y: 45
camera_pitch: [40, 41, 2]
camera_yaw: [0, 350, 36]
camera_save_image: False
camera_recon_scene: True
camera_lookat_pos: [1.3, 0.75, 0.4]

table_top: [1.3, 0.75, 0.4]
table_T_camR: [0, 0, 0]
cut_off_points: [0.3, 0.5, 0.5]  # for cropping pointcloud


render: False
bbox_indicator: False
randomize_color: True

initial_policies:

    grasp_dexnet_controller:
        fn: policy.grasp_dexnet_controller:GraspDexnetController
        params:
            max_path_length: 110
