accept_threshold: 0.8
env_base_xml_file: fetch/pick_and_place.xml
env_name: FetchPickAndPlace-v1
max_path_length: 50
num_rollouts: 5
num_threads: 5
clusters:
  c0:
    expert_name: grasp_from_rim_controller
    fn: policy.grasp_from_rim_controller:GraspFromRimController
    params:
      model_name: null
      policy_model_path: ''
      policy_name: grasp_from_rim_controller
  c1:
    expert_name: grasp_from_center_controller
    fn: policy.grasp_from_center_controller:GraspFromCenterController
    params:
      max_path_length: 110
      model_name: null
      policy_model_path: ''
      policy_name: grasp_from_center_controller
objs:
    '159e56c18906830278d8f8c02c47cde0':
        class_id: 0
        obj_xml_file: 'cups/159e56c18906830278d8f8c02c47cde0.xml'
        scale: 1.2
        cluster_id: c0
    '899af991203577f019790c8746d79a6f':
        class_id: 1
        obj_xml_file: 'bowls/899af991203577f019790c8746d79a6f.xml'
        scale: 2.0
        cluster_id: c0
    'e816066ac8281e2ecf70f9641eb97702':
        class_id: 1
        obj_xml_file: 'bowls/e816066ac8281e2ecf70f9641eb97702.xml'
        scale: 2.0
        cluster_id: c0
    '9024177b7ed352f45126f17934e17803':
        class_id: 1
        obj_xml_file: 'bowls/9024177b7ed352f45126f17934e17803.xml'
        scale: 2.0
        cluster_id: c0
    'a95e0d8b37f8ca436a3309b77df3f951':
        class_id: 1
        obj_xml_file: 'bowls/a95e0d8b37f8ca436a3309b77df3f951.xml'
        scale: 2.0
        cluster_id: c0
    '454fa7fd637177cf2bea4b6e7618432':
        class_id: 1
        obj_xml_file: 'bowls/454fa7fd637177cf2bea4b6e7618432.xml'
        scale: 2.0
        cluster_id: c0
    '54f2d6a0b431839c99785666a0fe0255':
        class_id: 0
        obj_xml_file: 'cups/54f2d6a0b431839c99785666a0fe0255.xml'
        scale: 1.5
        cluster_id: c0
    'b9004dcda66abf95b99d2a3bbaea842a':
        class_id: 0
        obj_xml_file: 'cups/b9004dcda66abf95b99d2a3bbaea842a.xml'
        scale: 1.0
        cluster_id: c0
    'c399bfee7f25f0ff95aab58c1db71c10':
        class_id: 1
        obj_xml_file: 'bowls/c399bfee7f25f0ff95aab58c1db71c10.xml'
        scale: 2.0
        cluster_id: c0
    'f99e19b8c4a729353deb88581ea8417a':
        class_id: 0
        obj_xml_file: 'cups/f99e19b8c4a729353deb88581ea8417a.xml'
        scale: 1.2
        cluster_id: c0
    'c0f57c7f98d2581c744a455c7eef0ae5':
        class_id: 1
        obj_xml_file: 'bowls/c0f57c7f98d2581c744a455c7eef0ae5.xml'
        scale: 2.0
        cluster_id: c0
    '27119d9b2167080ec190cb14324769d':
        class_id: 0
        obj_xml_file: 'cups/27119d9b2167080ec190cb14324769d.xml'
        scale: 1.5
        cluster_id: c0
    'pallet_mug':
        class_id: 2
        obj_xml_file: 'robotsuite_objects/pallet_mug.xml'
        cluster_id: c1
    'pen':
        class_id: 2
        obj_xml_file: 'robotsuite_objects/pen.xml'
        cluster_id: c1
    'bottle':
        class_id: 2
        obj_xml_file: 'robotsuite_objects/bottle.xml'
        cluster_id: c1
    'glass':
        class_id: 2
        obj_xml_file: 'robotsuite_objects/glass.xml'
        cluster_id: c1